### ISSUE TITLE
Channel has been closed

### ISSUE THREAD

**Issue by biswaKL** [Azure-Samples/azure-cosmos-db-cassandra-java-getting-started#2]
> Please provide us with the following information:
> ---------------------------------------------------------------
Unable to execute the code

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>[root@centos-s-1vcpu-1gb-blr1-01 java-examples]# java -cp target/cosmosdb-cassandra-examples.jar com.azure.cosmosdb.cassandra.examples.UserProfile
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: blrtsdb.cassandra.cosmos.azure.com/13.71.115.125:10350 (com.datastax.driver.core.exceptions.TransportException: [blrtsdb.cassandra.cosmos.azure.com/13.71.115.125:10350] Channel has been closed))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:232)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
        at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1600)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1518)
        at com.datastax.driver.core.Cluster.init(Cluster.java:159)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
        at com.azure.cosmosdb.cassandra.util.CassandraUtils.getSession(CassandraUtils.java:64)
        at com.azure.cosmosdb.cassandra.examples.UserProfile.main(UserProfile.java:26)

### Expected/desired behavior
>

### OS and Version?
> CentOS 7

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RubenEscribanoMartin** [comment]
> NoHostAvailableException

Hi, did you try to change your host? such as private String cassandraHost = "127.0.0.1";

**Comment by SindhuVarier** [comment]
Hi, was this resolved? I get the same exception not from sample but while connecting from Flink using similar Java v3 API.
